# gocov configuration file

# ディレクトリ階層の集計レベル
# 0: 末端ディレクトリごと（デフォルト）
# N (N > 0): パスの最初のN個の要素で集計
# -1: トップレベルで全体を集計
level: 0

# カバレッジ率のフィルタリング
coverage:
  # 表示する最小カバレッジ率（0-100）
  min: 0
  # 表示する最大カバレッジ率（0-100）
  max: 100

# 出力フォーマット
# table: 表形式（デフォルト）
# json: JSON形式
format: table

# 無視するディレクトリパターン
# ワイルドカード（*）が使用可能
ignore:
  - "*/vendor/*"
  - "*/test/*"
  - "*/mock/*"
  - "*/generated/*"